Repository Teradata/covalent, pull requests merged in 2018-08, with the labels that each got.

#1209 fix(breadcrumbs): clean up imports of observable creation methods
  src/platform/experimental/breadcrumbs/breadcrumbs.component.ts
Labels: code lgtm

#1211 refactor(dynamic-forms): remove ngModel usage
  src/platform/dynamic-forms/dynamic-element.component.ts
  src/platform/dynamic-forms/dynamic-elements/abstract-control-value-accesor.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-checkbox/dynamic-checkbox.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-checkbox/dynamic-checkbox.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-slide-toggle/dynamic-slide-toggle.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-slide-toggle/dynamic-slide-toggle.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-slider/dynamic-slider.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-slider/dynamic-slider.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.ts
Labels: code lgtm, ux lgtm

#1212 feat(dynamic-forms): add custom type support (closes #314)
  src/app/components/components/components.module.ts
  src/app/components/components/dynamic-forms/dynamic-forms.component.html
  src/app/components/components/dynamic-forms/dynamic-forms.component.ts
  src/platform/dynamic-forms/README.md
  src/platform/dynamic-forms/dynamic-element.component.ts
  src/platform/dynamic-forms/dynamic-forms.component.spec.ts
  src/platform/dynamic-forms/services/dynamic-forms.service.ts
Labels: code lgtm

#1222 fix(dynamic-forms): make sure hints and errors dont overlap
  src/app/components/components/dynamic-forms/dynamic-forms.component.html
  src/app/components/components/dynamic-forms/dynamic-forms.component.ts
  src/platform/dynamic-forms/README.md
  src/platform/dynamic-forms/dynamic-element.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.ts
  src/platform/dynamic-forms/dynamic-forms.component.html
Labels: code lgtm

#1201 feat(dynamic-forms): add support for Materials multiselect form field (closes #820)
  src/platform/dynamic-forms/dynamic-element.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.ts
  src/platform/dynamic-forms/dynamic-forms.component.html
  src/platform/dynamic-forms/services/dynamic-forms.service.ts
  src/test-bed/main/main.component.html
  src/test-bed/sandbox/multiselect/multiselect.component.html
  src/test-bed/sandbox/multiselect/multiselect.component.scss
  src/test-bed/sandbox/multiselect/multiselect.component.ts
  src/test-bed/test-bed.module.ts
  src/test-bed/test-bed.routes.ts
Labels: code lgtm

#1214 feat(animations): rotate animation params
  src/app/components/components/animations/animations.component.html
  src/app/components/components/animations/animations.component.ts
  src/platform/core/common/animations/rotate/rotate.animation.ts
  src/platform/core/expansion-panel/expansion-panel.component.ts
Labels: ready for review

#1008 feat(data-table): add ability to manually resize columns
  src/app/components/components/data-table/data-table.component.html
  src/app/components/components/data-table/data-table.component.ts
  src/platform/core/data-table/README.md
  src/platform/core/data-table/_data-table-theme.scss
  src/platform/core/data-table/data-table-column/data-table-column.component.html
  src/platform/core/data-table/data-table.component.html
  src/platform/core/data-table/data-table.component.scss
  src/platform/core/data-table/data-table.component.ts
Labels: ready for review

#1224 fix(docs): Add documentation about clickable input on datatable (closes #1010)
  src/platform/core/data-table/README.md
Labels: code lgtm

#1228 feat(animations): collapse animation params
  src/app/components/components/animations/animations.component.html
  src/app/components/components/animations/animations.component.ts
  src/app/components/components/components.module.ts
  src/platform/core/common/animations/collapse/collapse.animation.ts
Labels: ready for review

#1231 feat(notification): limit added
  src/app/components/components/notifications/notifications.component.html
  src/platform/core/notifications/README.md
  src/platform/core/notifications/notification-count.component.spec.ts
  src/platform/core/notifications/notification-count.component.ts
Labels: ready for review
