Repository Teradata/covalent, pull requests merged in 2018-10, with the labels that each got.

#1240 feat(): Add timeUntil pipe
  src/app/components/components/pipes/pipes.component.html
  src/app/components/components/pipes/pipes.component.ts
  src/platform/core/common/common.module.ts
  src/platform/core/common/pipes/time-until/time-until.pipe.spec.ts
  src/platform/core/common/pipes/time-until/time-until.pipe.ts
Labels: code lgtm, ux lgtm

#1247 fix(chips): mobile select
  src/platform/core/chips/chips.component.ts
Labels: code lgtm

#1248 fix(chips): long texts
  src/app/components/components/chips/chips.component.html
  src/platform/core/chips/chips.component.scss
Labels: code lgtm

#1244 fix(dynamic-forms): added name to dynamic elements
  src/platform/dynamic-forms/dynamic-element.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-checkbox/dynamic-checkbox.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-checkbox/dynamic-checkbox.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-datepicker/dynamic-datepicker.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-file-input/dynamic-file-input.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-input/dynamic-input.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-select/dynamic-select.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-slide-toggle/dynamic-slide-toggle.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-slide-toggle/dynamic-slide-toggle.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-slider/dynamic-slider.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-slider/dynamic-slider.component.ts
  src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.html
  src/platform/dynamic-forms/dynamic-elements/dynamic-textarea/dynamic-textarea.component.ts
  src/platform/dynamic-forms/dynamic-forms.component.html
Labels: code lgtm, ready for review

#1213 feat(animation): params feature
  src/app/components/components/animations/animations.component.html
  src/app/components/components/animations/animations.component.ts
  src/app/components/components/components.module.ts
  src/app/components/components/virtual-scroll/virtual-scroll.component.ts
  src/platform/core/common/animations/bounce/bounce.animation.ts
  src/platform/core/common/animations/collapse/collapse.animation.ts
  src/platform/core/common/animations/fade/fadeInOut.animation.ts
  src/platform/core/common/animations/flash/flash.animation.ts
  src/platform/core/common/animations/headshake/headshake.animation.ts
  src/platform/core/common/animations/jello/jello.animation.ts
  src/platform/core/common/animations/pulse/pulse.animation.ts
  src/platform/core/common/animations/rotate/rotate.animation.ts
  src/platform/core/expansion-panel/expansion-panel.component.ts
  src/platform/core/json-formatter/json-formatter.component.ts
  src/platform/core/layout/navigation-drawer/navigation-drawer.component.ts
  src/platform/core/loading/loading.component.ts
  src/platform/core/message/message.component.ts
  src/platform/core/steps/step-body/step-body.component.ts
  src/universal-app/combat-training/combat-training.ts
Labels: ready for review

#1252 feat(upgrade): upgrade to us angular 7 rc.0/1
  angular.json
  build.conf.js
  package.json
  src/_teradata-branding.scss
  src/app/components/components/dynamic-forms/dynamic-forms.component.scss
  src/app/components/components/markdown/markdown.component.html
  src/app/components/components/virtual-scroll/virtual-scroll.component.html
  src/app/components/layouts/card-over/card-over.component.html
  src/app/components/layouts/manage-list/manage-list.component.html
  src/app/components/layouts/nav-list/nav-list.component.html
  src/app/components/layouts/nav-view/nav-view.component.html
  src/app/components/style-guide/logo/logo.component.html
  src/platform/core/common/animations/collapse/collapse.animation.ts
  src/platform/core/common/animations/fade/fadeInOut.animation.ts
  src/platform/core/common/styles/_elevation.scss
  src/platform/core/expansion-panel/expansion-panel.component.spec.ts
  src/platform/core/expansion-panel/expansion-panel.component.ts
  src/platform/core/file/directives/file-drop.directive.ts
  src/platform/core/json-formatter/json-formatter.component.spec.ts
  src/platform/core/layout/layout-manage-list/layout-manage-list.component.scss
  src/platform/core/layout/layout-nav-list/layout-nav-list.component.scss
  src/platform/core/layout/layout.component.scss
  src/platform/core/loading/directives/loading.directive.spec.ts
  src/platform/core/steps/steps.component.spec.ts
  src/polyfills.ts
  src/tests/utilities/covalent-tests.ts
  src/universal-app/package.json
  yarn.lock
Labels: ready for review

#1264 feat(breadcrumbs): graduation from experimental to core
  src/app/components/components/breadcrumbs/breadcrumbs.component.html
  src/app/components/components/breadcrumbs/breadcrumbs.component.scss
  src/app/components/components/breadcrumbs/breadcrumbs.component.ts
  src/app/components/components/components.component.ts
  src/app/components/components/components.module.ts
  src/app/components/components/components.routes.ts
  src/app/components/components/overview/overview.component.ts
  src/platform/core/breadcrumbs/README.md
  src/platform/core/breadcrumbs/_breadcrumbs-theme.scss
  src/platform/core/breadcrumbs/breadcrumb/breadcrumb.component.html
  src/platform/core/breadcrumbs/breadcrumb/breadcrumb.component.scss
  src/platform/core/breadcrumbs/breadcrumb/breadcrumb.component.spec.ts
  src/platform/core/breadcrumbs/breadcrumb/breadcrumb.component.ts
  src/platform/core/breadcrumbs/breadcrumbs.component.html
  src/platform/core/breadcrumbs/breadcrumbs.component.scss
  src/platform/core/breadcrumbs/breadcrumbs.component.spec.ts
  src/platform/core/breadcrumbs/breadcrumbs.component.ts
  src/platform/core/breadcrumbs/breadcrumbs.module.ts
  src/platform/core/breadcrumbs/index.ts
  src/platform/core/breadcrumbs/package.json
  src/platform/core/breadcrumbs/public-api.ts
  src/platform/core/public-api.ts
  src/platform/core/theming/_all-theme.scss
  src/platform/experimental/breadcrumbs/index.ts
  src/platform/experimental/theming/_all-theme.scss
  src/platform/ng-package-common.js
  src/test-bed/main/main.component.html
  src/test-bed/sandbox/breadcrumbs/breadcrumbs.component.html
  src/test-bed/test-bed.module.ts
  src/test-bed/test-bed.routes.ts
Labels: ready for review

#1256 feat(Navigational Stepper): *experimental*
  src/platform/experimental/nav-stepper/README.md
  src/platform/experimental/nav-stepper/horizontal-nav-stepper/horizontal-nav-stepper.component.html
  src/platform/experimental/nav-stepper/horizontal-nav-stepper/horizontal-nav-stepper.component.scss
  src/platform/experimental/nav-stepper/horizontal-nav-stepper/horizontal-nav-stepper.component.spec.ts
  src/platform/experimental/nav-stepper/horizontal-nav-stepper/horizontal-nav-stepper.component.ts
  src/platform/experimental/nav-stepper/index.ts
  src/platform/experimental/nav-stepper/nav-step-header/nav-step-header.component.html
  src/platform/experimental/nav-stepper/nav-step-header/nav-step-header.component.scss
  src/platform/experimental/nav-stepper/nav-step-header/nav-step-header.component.ts
  src/platform/experimental/nav-stepper/nav-step/_nav-step-theme.scss
  src/platform/experimental/nav-stepper/nav-step/nav-step.component.html
  src/platform/experimental/nav-stepper/nav-step/nav-step.component.scss
  src/platform/experimental/nav-stepper/nav-step/nav-step.component.ts
  src/platform/experimental/nav-stepper/nav-stepper.module.ts
  src/platform/experimental/nav-stepper/package.json
  src/platform/experimental/nav-stepper/public-api.ts
  src/platform/experimental/public-api.ts
  src/platform/experimental/theming/_all-theme.scss
  src/test-bed/main/main.component.html
  src/test-bed/sandbox/nav-stepper/nav-stepper.component.html
  src/test-bed/sandbox/nav-stepper/nav-stepper.component.scss
  src/test-bed/sandbox/nav-stepper/nav-stepper.component.ts
  src/test-bed/test-bed.module.ts
  src/test-bed/test-bed.routes.ts
Labels: ready for review
