Repository Teradata/covalent, pull requests merged in 2018-12, with the labels that each got.

#1305 feat(http): create http-deprec package for `@angular/http` use
  scripts/build-release
  src/platform/http-deprec/README.md
  src/platform/http-deprec/http-rest.service.spec.ts
  src/platform/http-deprec/http-rest.service.ts
  src/platform/http-deprec/http.module.ts
  src/platform/http-deprec/index.ts
  src/platform/http-deprec/interceptors/README.md
  src/platform/http-deprec/interceptors/http-interceptor-mapping.interface.ts
  src/platform/http-deprec/interceptors/http-interceptor-matcher.interface.ts
  src/platform/http-deprec/interceptors/http-interceptor.interface.ts
  src/platform/http-deprec/interceptors/http-interceptor.service.spec.ts
  src/platform/http-deprec/interceptors/http-interceptor.service.ts
  src/platform/http-deprec/interceptors/url-regexp-interceptor-matcher.class.spec.ts
  src/platform/http-deprec/interceptors/url-regexp-interceptor-matcher.class.ts
  src/platform/http-deprec/ng-package.js
  src/platform/http-deprec/package.json
  src/platform/http-deprec/public-api.ts
Labels: deprecate

#1310 feat(http): use HttpClient instead of Http and improve API usage + http decorators **BREAKING CHANGE**
  src/app/components/components/http/http.component.html
  src/app/components/components/http/http.component.ts
  src/platform/experimental/http/actions/class/http.decorator.ts
  src/platform/experimental/http/index.ts
  src/platform/experimental/http/package.json
  src/platform/experimental/http/public-api.ts
  src/platform/experimental/package.json
  src/platform/http/README.md
  src/platform/http/actions/README.md
  src/platform/http/actions/class/http.decorator.ts
  src/platform/http/actions/http.mixin.spec.ts
  src/platform/http/actions/http.mixin.ts
  src/platform/http/actions/index.ts
  src/platform/http/actions/methods/abstract-method.decorator.ts
  src/platform/http/actions/methods/delete.decorator.ts
  src/platform/http/actions/methods/get.decorator.ts
  src/platform/http/actions/methods/patch.decorator.ts
  src/platform/http/actions/methods/post.decorator.ts
  src/platform/http/actions/methods/put.decorator.ts
  src/platform/http/actions/params/abstract-param.decorator.ts
  src/platform/http/actions/params/body.decorator.ts
  src/platform/http/actions/params/param.decorator.ts
  src/platform/http/actions/params/query-params.decorator.ts
  src/platform/http/actions/params/response.decorator.ts
  src/platform/http/http-rest.service.spec.ts
  src/platform/http/http-rest.service.ts
  src/platform/http/http.interfaces.ts
  src/platform/http/http.module.ts
  src/platform/http/interceptors/README.md
  src/platform/http/interceptors/http-interceptor-mapping.interface.ts
  src/platform/http/interceptors/http-interceptor-matcher.interface.ts
  src/platform/http/interceptors/http-interceptor.interface.ts
  src/platform/http/interceptors/http-interceptor.service.spec.ts
  src/platform/http/interceptors/http-interceptor.service.ts
  src/platform/http/interceptors/http.service.spec.ts
  src/platform/http/interceptors/http.service.ts
  src/platform/http/interceptors/url-regexp-interceptor-matcher.class.spec.ts
  src/platform/http/interceptors/url-regexp-interceptor-matcher.class.ts
  src/platform/http/package.json
  src/platform/http/public-api.ts
  src/test-bed/main/main.component.html
  src/test-bed/sandbox/http/http.component.html
  src/test-bed/sandbox/http/http.component.ts
  src/test-bed/sandbox/http/test-http.service.ts
  src/test-bed/test-bed.module.ts
  src/test-bed/test-bed.routes.ts
Labels: breaking change

#1306 Add accordion mode to td-expansion-panel-group *Breaking Change*
  src/app/components/components/expansion-panel/expansion-panel.component.html
  src/app/components/components/expansion-panel/expansion-panel.component.ts
  src/platform/core/expansion-panel/README.md
  src/platform/core/expansion-panel/expansion-panel-group.component.spec.ts
  src/platform/core/expansion-panel/expansion-panel-group.component.ts
Labels: breaking change

#1307 feat(nav-steps): graduation from experimental to core
  src/app/components/components/components.component.ts
  src/app/components/components/components.module.ts
  src/app/components/components/components.routes.ts
  src/app/components/components/nav-steps/nav-steps.component.html
  src/app/components/components/nav-steps/nav-steps.component.scss
  src/app/components/components/nav-steps/nav-steps.component.ts
  src/app/components/components/overview/overview.component.ts
  src/app/components/toolbar/toolbar.component.html
  src/platform/core/steps/_steps-theme.scss
  src/platform/core/steps/nav/README.md
  src/platform/core/steps/nav/nav-step-link/nav-step-link.component.html
  src/platform/core/steps/nav/nav-step-link/nav-step-link.component.scss
  src/platform/core/steps/nav/nav-step-link/nav-step-link.component.ts
  src/platform/core/steps/nav/nav-steps-horizontal/nav-steps-horizontal.component.html
  src/platform/core/steps/nav/nav-steps-horizontal/nav-steps-horizontal.component.scss
  src/platform/core/steps/nav/nav-steps-horizontal/nav-steps-horizontal.component.spec.ts
  src/platform/core/steps/nav/nav-steps-horizontal/nav-steps-horizontal.component.ts
  src/platform/core/steps/nav/nav-steps-vertical/nav-steps-vertical.component.html
  src/platform/core/steps/nav/nav-steps-vertical/nav-steps-vertical.component.scss
  src/platform/core/steps/nav/nav-steps-vertical/nav-steps-vertical.component.spec.ts
  src/platform/core/steps/nav/nav-steps-vertical/nav-steps-vertical.component.ts
  src/platform/core/steps/step-header/step-header.component.scss
  src/platform/core/steps/steps.component.ts
  src/platform/core/steps/steps.module.ts
  src/platform/experimental/nav-stepper/README.md
  src/platform/experimental/nav-stepper/horizontal-nav-stepper/horizontal-nav-stepper.component.html
  src/platform/experimental/nav-stepper/horizontal-nav-stepper/horizontal-nav-stepper.component.scss
  src/platform/experimental/nav-stepper/horizontal-nav-stepper/horizontal-nav-stepper.component.spec.ts
  src/platform/experimental/nav-stepper/horizontal-nav-stepper/horizontal-nav-stepper.component.ts
  src/platform/experimental/nav-stepper/index.ts
  src/platform/experimental/nav-stepper/nav-step-header/nav-step-header.component.html
  src/platform/experimental/nav-stepper/nav-step-header/nav-step-header.component.scss
  src/platform/experimental/nav-stepper/nav-step-header/nav-step-header.component.ts
  src/platform/experimental/nav-stepper/nav-step/_nav-step-theme.scss
  src/platform/experimental/nav-stepper/nav-step/nav-step.component.html
  src/platform/experimental/nav-stepper/nav-step/nav-step.component.scss
  src/platform/experimental/nav-stepper/nav-step/nav-step.component.ts
  src/platform/experimental/nav-stepper/nav-stepper.module.ts
  src/platform/experimental/nav-stepper/package.json
  src/platform/experimental/nav-stepper/public-api.ts
  src/platform/experimental/public-api.ts
  src/platform/experimental/theming/_all-theme.scss
  src/test-bed/main/main.component.html
  src/test-bed/sandbox/nav-stepper/nav-stepper.component.html
  src/test-bed/sandbox/nav-stepper/nav-stepper.component.ts
  src/test-bed/test-bed.module.ts
  src/test-bed/test-bed.routes.ts
  src/theme.scss
Labels: ready for review
