Repository Teradata/covalent, pull requests merged in 2019-06, with the labels that each got.

#1375 Upgrade to gulp 4.0.0, remove vulnerabilities from 3.x
  gulpfile.js
  package-lock.json
  package.json
  scripts/build-schematics.js
  scripts/bump-version.js
  scripts/post-ng-packagr-build.js
  scripts/version-placeholders.js
Labels: code lgtm

#1370 fix(audit): update packages to solve all `npm audit` issues
  .travis.yml
  package-lock.json
  package.json
  scripts/ci/travis-script.sh
  src/platform/core/chips/chips.component.scss
  src/platform/core/common/styles/_layout.scss
  src/platform/core/data-table/data-table-cell/data-table-cell.component.scss
  src/platform/core/expansion-panel/expansion-panel.component.scss
  src/platform/core/json-formatter/json-formatter.component.scss
  src/platform/core/layout/layout-nav-list/layout-nav-list.component.scss
  src/platform/core/layout/layout-nav/layout-nav.component.scss
  src/platform/core/layout/navigation-drawer/navigation-drawer.component.scss
  src/platform/core/message/message.component.scss
  src/platform/core/steps/nav/nav-step-link/nav-step-link.component.scss
  src/platform/core/steps/nav/nav-steps-horizontal/nav-steps-horizontal.component.scss
  src/platform/core/steps/step-header/step-header.component.scss
  src/platform/dynamic-forms/dynamic-forms.component.scss
Labels: code lgtm, ready for review, ux lgtm

#1367 docs(data-table): fix inconsistencies in README
  src/platform/core/data-table/README.md
Labels: code lgtm, ready to merge, ux lgtm

#1346 docs: correct bounded expression
  src/platform/core/layout/README.md
Labels: code lgtm

#1357 fix(): a11y visual fixes home
  scripts/a11y/routes.txt
  src/app/components/home/home.component.html
Labels: code lgtm, ready for review

#1389 Add help component
  package-lock.json
  package.json
  scripts/build-release
  src/app/components/components/components.component.html
  src/app/components/components/components.component.ts
  src/app/components/components/components.module.ts
  src/app/components/components/components.routes.ts
  src/app/components/components/flavored-markdown/flavored-markdown.component.html
  src/app/components/components/help/help.component.html
  src/app/components/components/help/help.component.scss
  src/app/components/components/help/help.component.ts
  src/app/components/components/markdown/markdown.component.html
  src/app/components/components/markdown/markdown.component.ts
  src/app/documentation-tools/readme-loader/readme-loader.component.html
  src/app/documentation-tools/readme-loader/readme-loader.component.ts
  src/platform/experimental/help/README.md
  src/platform/experimental/help/draggable-help-window-dialog/draggable-help-window-dialog.component.html
  src/platform/experimental/help/draggable-help-window-dialog/draggable-help-window-dialog.component.scss
  src/platform/experimental/help/draggable-help-window-dialog/draggable-help-window-dialog.component.ts
  src/platform/experimental/help/draggable-help-window-dialog/draggable-help-window-dialog.service.ts
  src/platform/experimental/help/help-window/help-window-toolbar/help-window-toolbar.component.html
  src/platform/experimental/help/help-window/help-window-toolbar/help-window-toolbar.component.scss
  src/platform/experimental/help/help-window/help-window-toolbar/help-window-toolbar.component.ts
  src/platform/experimental/help/help-window/help-window.component.html
  src/platform/experimental/help/help-window/help-window.component.scss
  src/platform/experimental/help/help-window/help-window.component.ts
  src/platform/experimental/help/help.component.html
  src/platform/experimental/help/help.component.scss
  src/platform/experimental/help/help.component.ts
  src/platform/experimental/help/help.module.ts
  src/platform/experimental/help/help.utils.ts
  src/platform/experimental/help/index.ts
  src/platform/experimental/help/package.json
  src/platform/experimental/help/public-api.ts
  src/platform/flavored-markdown/README.md
  src/platform/flavored-markdown/flavored-markdown-loader/flavored-markdown-loader.component.html
  src/platform/flavored-markdown/flavored-markdown-loader/flavored-markdown-loader.component.scss
  src/platform/flavored-markdown/flavored-markdown-loader/flavored-markdown-loader.component.ts
  src/platform/flavored-markdown/flavored-markdown.component.ts
  src/platform/flavored-markdown/flavored-markdown.module.ts
  src/platform/flavored-markdown/public_api.ts
  src/platform/markdown/README.md
  src/platform/markdown/markdown-loader.service.ts
  src/platform/markdown/markdown-utils.ts
  src/platform/markdown/markdown.component.spec.ts
  src/platform/markdown/markdown.component.ts
  src/platform/markdown/public_api.ts
Labels: ready for review

#1354 fix(): a11y code batch 0
  docs/CHANGELOG.md
  docs/GETTING_STARTED.md
  docs/UTILITY_MIXINS.md
  scripts/a11y/a11y.sh
  src/app/app.routes.ts
  src/app/components/toolbar/toolbar.component.html
  src/index.html
  src/platform/core/README.md
  src/platform/core/layout/README.md
  src/test-bed/test-bed.routes.ts
Labels: code lgtm, ready to merge

#1355 feat(highlight) deprecate lang input in favor of codeLang
  src/app/components/components/animations/animations.component.html
  src/app/components/components/breadcrumbs/breadcrumbs.component.html
  src/app/components/components/chips/chips.component.html
  src/app/components/components/code-editor/code-editor.component.html
  src/app/components/components/data-table/data-table.component.html
  src/app/components/components/dialogs/dialogs.component.html
  src/app/components/components/directives/directives.component.html
  src/app/components/components/dynamic-forms/dynamic-forms.component.html
  src/app/components/components/expansion-panel/expansion-panel.component.html
  src/app/components/components/file-input/file-input.component.html
  src/app/components/components/file-upload/file-upload.component.html
  src/app/components/components/flavored-markdown/flavored-markdown.component.html
  src/app/components/components/highlight/highlight.component.html
  src/app/components/components/json-formatter/json-formatter.component.html
  src/app/components/components/loading/loading.component.html
  src/app/components/components/markdown/markdown.component.html
  src/app/components/components/media/media.component.html
  src/app/components/components/message/message.component.html
  src/app/components/components/nav-steps/nav-steps.component.html
  src/app/components/components/ngx-translate/ngx-translate.component.html
  src/app/components/components/notifications/notifications.component.html
  src/app/components/components/paging/paging.component.html
  src/app/components/components/pipes/pipes.component.html
  src/app/components/components/steps/steps.component.html
  src/app/components/components/tab-select/tab-select.component.html
  src/app/components/components/virtual-scroll/virtual-scroll.component.html
  src/app/components/docs/build-tasks/build-tasks.component.html
  src/app/components/docs/creating/creating.component.html
  src/app/components/docs/deployment/deployment.component.html
  src/app/components/docs/icons/icons.component.html
  src/app/components/docs/mock-data/mock-data.component.html
  src/app/components/docs/testing/testing.component.html
  src/app/components/docs/theme/theme.component.html
  src/app/components/layouts/card-over/card-over.component.html
  src/app/components/layouts/manage-list/manage-list.component.html
  src/app/components/layouts/nav-list/nav-list.component.html
  src/app/components/layouts/nav-view/nav-view.component.html
  src/app/components/layouts/overview/overview.component.html
  src/app/components/style-guide/colors/colors.component.html
  src/app/components/style-guide/iconography/iconography.component.html
  src/app/components/style-guide/logo/logo.component.html
  src/app/components/style-guide/product-icons/product-icons.component.html
  src/app/components/style-guide/utility-styles/utility-styles.component.html
  src/platform/flavored-markdown/flavored-markdown.component.ts
  src/platform/highlight/README.md
  src/platform/highlight/highlight.component.spec.ts
  src/platform/highlight/highlight.component.ts
Labels: ready for review

#1405 fix(td-help): handle non raw image urls
  src/platform/markdown/markdown.component.spec.ts
  src/platform/markdown/markdown.component.ts
Labels: ready for review
